# Generated by Django 5.1.1 on 2024-10-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='registered_at',
        ),
        migrations.AddField(
            model_name='registration',
            name='contact',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
