# Generated by Django 5.1.1 on 2024-10-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='/event_images/default.png', null=True, upload_to='event_images/'),
        ),
    ]
